@startuml caso_de_uso_puzzle

:Main user: as User <<Jugador>>

package System{
    usecase "Jugar"
    usecase "Mover"
    usecase "Verificar"
}

User --> "Jugar" : Oprimir flecha

"Jugar" --> "Verificar" 
"Jugar" --> "Mover"

@enduml
