' RECORDAR: En UML en los cass de uso, se colocan los verbos en infinitivo
' como lo es: "Jugar , Mover , Verifivar , etc"

' << -- >> se usa para poner estereotipos a los actores

@startuml caso_de_uso_puzzle

:Main user: as User <<Jugador>>

package System{
    usecase "Jugar"
    usecase "Mover"
    usecase "Verificar"
}

User --> "Jugar" : Oprimir flecha

"Jugar" --> "Verificar" 
"Jugar" --> "Mover"

@enduml
